name: opendata_parser
description: opendata_parser
version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  tree_converter: tree_converter.dart
  stolpersteine_converter: stolpersteine_converter.dart


dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.2
  http: ^0.12.0+1
