name: tree_parser
description: tree_parser
version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'


executables:
  converter:

dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.2
